export const CATEGORIES = [
  { id: 'restaurant', label: 'Restaurants', icon: 'restaurant' as const },
  { id: 'cafe', label: 'Cafés', icon: 'cafe' as const },
  { id: 'bar', label: 'Bars', icon: 'beer' as const },
  { id: 'hotel', label: 'Hotels', icon: 'bed' as const },
  { id: 'fast_food', label: 'Fast Food', icon: 'fast-food' as const },
  { id: 'parking', label: 'Parking', icon: 'car' as const },
  { id: 'theatre', label: 'Theatre', icon: 'film' as const },
  { id: 'ferry_terminal', label: 'Ferry', icon: 'boat' as const },
  { id: 'car_rental', label: 'Car Rental', icon: 'key' as const },
  { id: 'conference_centre', label: 'Conference', icon: 'business' as const },
  { id: 'park', label: 'Park', icon: 'leaf' as const },
  { id: 'shopping_mall', label: 'Shopping Mall', icon: 'cart' as const },
  { id: 'gym', label: 'Gym', icon: 'barbell' as const },
  { id: 'hospital', label: 'Hospital', icon: 'medkit' as const },
  { id: 'studio', label: 'Studio', icon: 'musical-note' as const },
  { id: 'atm', label: 'ATM', icon: 'card' as const },
  { id: 'kontantuttag', label: 'ATM', icon: 'card' as const },
  { id: 'post_office', label: 'Post Office', icon: 'mail' as const },
  { id: 'university', label: 'University', icon: 'school' as const },
  { id: 'community_centre', label: 'Community Centre', icon: 'people' as const },
  { id: 'cinema', label: 'Cinema', icon: 'film' as const },
  { id: 'clinic', label: 'Clinic', icon: 'medkit' as const },
  { id: 'dentist', label: 'Dentist', icon: 'medkit' as const },
  { id: 'pub', label: 'Pub', icon: 'beer' as const },
  { id: 'place_of_worship', label: 'Place of Worship', icon: 'planet' as const },
  { id: 'college', label: 'College', icon: 'school' as const },
  { id: 'bank', label: 'Bank', icon: 'cash' as const },
  { id: 'Kontantuttag', label: 'ATM', icon: 'card' as const },
  { id: 'driving_school', label: 'Driving School', icon: 'car' as const },
] as const
